root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  kb/article/42-code-of-conduct: gitcoin-policy/code-of-conduct.md
  gitcoin-knowledge-base/gitcoin-passport/what-is-gitcoin-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/creating-a-gitcoin-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/what-are-stamps: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/navigating-your-ethereum-stamp-insights-and-updates: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/understanding-your-eligibility-for-the-gitcoin-grants-stamp-on-gitcoin-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/moving-your-stamps-onchain: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/presenting-your-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/identity-staking-questions: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/identity-staking-questions/gtc-staking-faq: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/identity-staking-questions/how-to-ask-a-friend-to-participate-in-identity-staking: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/identity-staking-questions/guide-to-unstaking-staked-gtc-tokens-via-etherscan-with-walletconnect: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/passport-api-and-smart-contracts: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-create-a-gitcoin-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-a-google-account-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-a-linkedin-stamp-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-a-discord-account-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-a-github-account-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-an-ens-account-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-a-twitter-account-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-lens-stamp-to-gitcoin-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-holonym-stamp-to-gitcoin-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-trusta-labs-stamp-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-brightid-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-coinbase-stamp-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-snapshot-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-gitcoin-grants-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-gitcoin-grants-to-passport-1: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-gitcoin-grants-to-passport-2: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-gitcoin-grants-to-passport-3: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-civic-stamp-verification-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-guild-stamp-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-a-proof-of-humanity-poh-account-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-a-proof-of-humanity-poh-account-to-passport-1: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/connecting-gitcoin-grants-to-passport-4: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/verifying-ethereum-transactions-to-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/why-do-i-need-to-rescore-my-passport-after-collecting-a-new-stamp: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/how-is-gitcoin-passports-score-calculated: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/how-do-i-unlink-a-passport-from-my-gitcoin-account: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/why-have-my-stamps-expired: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/what-is-ceramic: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/why-is-my-passport-score-not-adding-up: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/can-a-developer-add-a-new-stamp-to-gitcoin-passport: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/can-i-integrate-gitcoin-passport-into-my-dapp: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/how-to-access-your-passport-json: misc/passport.md
  gitcoin-knowledge-base/gitcoin-passport/common-questions/how-to-download-your-passport-json: misc/passport.md